### ISSUE TITLE
npm run watch fails

### ISSUE THREAD

**Issue by SamuelToh** [gh0st/ncps-mms#1]
Was trying to do "npm run watch" by following the Setup instructions from README.md.

**From Readme**
Have MongoDB installed and running, and NodeJS installed.

- cd into the package.
- Run npm install to resolve project dependencies.
- Run npm install -g gulp to install Gulp globally.
- Run npm run watch to start transpile watch. This command will read files under client/src and generate a single file under client/dist/bundle.js which should be included in the index.html.
- Launch your browser and visit localhost:3030. 

Failed on the npm run watch step. Note this is on a computer which has never got Gulp installed.
This is the error I am having

**ERROR**
```
tigerroarz@tigerroarz-Latitude-E6520:~/github/ncps-mms$ npm run watch

> ncps-mms@0.0.0 watch /home/tigerroarz/github/ncps-mms
> gulp watch --gulpfile client/gulpfile.babel.js

[21:40:44] Requiring external module babel-register
[21:40:44] Working directory changed to ~/github/ncps-mms/client
/home/tigerroarz/github/ncps-mms/client/gulpfile.babel.js:3
import gulp from "gulp";
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/tigerroarz/github/ncps-mms/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/tigerroarz/github/ncps-mms/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (/home/tigerroarz/github/ncps-mms/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/tigerroarz/github/ncps-mms/node_modules/liftoff/index.js:193:16)

npm ERR! Linux 4.2.0-19-generic
npm ERR! argv "/home/tigerroarz/.nvm/versions/node/v5.9.1/bin/node" "/home/tigerroarz/.nvm/versions/node/v5.9.1/bin/npm" "run" "watch"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! ncps-mms@0.0.0 watch: `gulp watch --gulpfile client/gulpfile.babel.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ncps-mms@0.0.0 watch script 'gulp watch --gulpfile client/gulpfile.babel.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ncps-mms package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp watch --gulpfile client/gulpfile.babel.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ncps-mms
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ncps-mms
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tigerroarz/github/ncps-mms/npm-debug.log
```

Are we missing something in the package.json? Any help will be greatly appreciated.

**Comment by gh0st** [comment]
Whoops, I think this might because you don't have gulp installed globally. Try an `npm install -g gulp` to install gulp globally and that should resolve this issue. I need to include that in the requirements of the readme if that is the fix.

**Comment by gh0st** [comment]
Oops, it's already in the readme. Did you not run `npm install -g gulp` like you pasted in your original issue?
